### ISSUE TITLE
fix: Running tests on static scaffolding gives errors

### ISSUE THREAD

**Issue by fedomain** [sjhorn/mason_bricks#1]
**Brick**

- [x] model
- [ ] feature_brick
- [ ] app_ui
- [x] service
- [ ] service_package

**Description**
Running the unit tests on static scaffolding did not pass all the auto generated tests. 

**Steps To Reproduce**

1. Follow the instructions on installing and generating the static scaffolding including tests and home
2. Make sure mason, mocktail, bloc_test is installed
3. Run the test
4. Result is not 100% passed

**Expected Behavior**
100% tests passed

**Screenshots**
<img width="1792" alt="Screenshot 2023-01-15 at 6 42 14 PM" src="https://user-images.githubusercontent.com/1567405/213199981-6eebed73-25ca-4241-9c5a-1a93e68dc68d.png">

**Additional Context**
I just followed the instructions on the documentation for standing up static scaffolding and then ran the test straight after.

**Comment by sjhorn** [comment]
Thanks @fedomain - I have created a fix for these issues and incorporated back into the scaffolding_test brick.
